# Generated by Django 3.2.5 on 2021-11-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='members',
            constraint=models.UniqueConstraint(fields=('club', 'user'), name='member of a club only once'),
        ),
    ]
