# Generated by Django 3.2.5 on 2021-11-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_members_member of a club only once'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gravatar',
            field=models.ImageField(blank=True, upload_to='gravatar_uploads/'),
        ),
    ]
