# Generated by Django 3.2.5 on 2021-11-17 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_user_chess_experience_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chess_experience_level',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
