# Generated by Django 3.2.5 on 2021-11-19 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_alter_user_chess_experience_level'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
