# Generated by Django 3.2.5 on 2021-11-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20211127_1535'),
        ('clubs', '0007_events'),
        ('clubs', '0008_events'),
    ]

    operations = [
    ]
