# Generated by Django 3.2.5 on 2021-11-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_merge_0007_auto_20211127_1535_0007_events_0008_events'),
        ('clubs', '0009_merge_0007_auto_20211127_1535_0008_events'),
    ]

    operations = [
    ]
