# Generated by Django 3.2.5 on 2021-12-01 00:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_merge_0007_auto_20211127_1535_0008_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='action',
            field=models.IntegerField(choices=[(1, 'Accepted'), (2, 'Applied'), (3, 'Rejected'), (4, 'Promoted'), (5, 'Demoted'), (6, 'Kicked')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
