# Generated by Django 3.2.5 on 2021-12-06 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_auto_20211205_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='capacity',
            field=models.IntegerField(default=96, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(96)]),
        ),
    ]
