# Generated by Django 3.2.5 on 2021-12-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_rename_members_membership'),
        ('clubs', '0012_tournament_capacity'),
    ]

    operations = [
    ]
