# Generated by Django 3.2.5 on 2021-12-14 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_alter_tournament_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_round',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
