# Generated by Django 3.2.5 on 2021-12-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_alter_match_match_status'),
        ('clubs', '0015_match_match_round'),
    ]

    operations = [
    ]
