# Generated by Django 3.2.5 on 2021-12-15 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_merge_20211215_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_round',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
