# Generated by Django 3.2.5 on 2021-12-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_alter_tournament_capacity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('tournament', 'member'), name='Participant of a tournament only once'),
        ),
    ]
