# Generated by Django 3.2.5 on 2021-12-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_participant_participant of a tournament only once'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='coorganisers',
            field=models.ManyToManyField(blank=True, to='clubs.Membership'),
        ),
    ]
