# Generated by Django 3.2.5 on 2021-12-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0021_auto_20211216_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.CharField(max_length=260),
        ),
    ]
