# Generated by Django 3.2.5 on 2021-12-17 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0022_alter_tournament_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='action',
            field=models.IntegerField(choices=[(1, 'Accepted'), (2, 'Applied'), (3, 'Rejected'), (4, 'Promoted'), (5, 'Demoted'), (6, 'Kicked'), (7, 'Left')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
